# Generated by Django 4.2.3 on 2023-11-29 22:18

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=200, validators=[news.validators.validate_name]
            ),
        ),
    ]
