# Generated by Django 4.2.3 on 2023-11-29 22:40

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_category_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        validators=[news.validators.validate_name],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=200,
                        unique=True,
                        validators=[news.validators.validate_name],
                    ),
                ),
                ("password", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        max_length=200,
                        validators=[news.validators.validate_name],
                    ),
                ),
            ],
        ),
    ]
