# Generated by Django 4.2.3 on 2023-11-29 23:09

from django.db import migrations, models
import django.db.models.deletion
import news.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[
                            news.validators.validate_empty,
                            news.validators.validate_title,
                        ],
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        validators=[news.validators.validate_empty]
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="img/"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        validators=[news.validators.validate_empty],
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.user",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="news", to="news.category"
                    ),
                ),
            ],
        ),
    ]
